name: Deploy Angular App to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Angular project
      run: npm run build --prod

    - name: Deploy to Google Cloud VM
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        ssh -o StrictHostKeyChecking=no rishitpalle@35.228.195.201 "
          # Clean the Apache HTML folder
          sudo rm -rf /var/www/html/* || true;

          # Create the HTML directory if it doesn't exist
          sudo mkdir -p /var/www/html;
        "

        # Copy the built project to the server
        scp -r dist/portfolio/* rishitpalle@35.228.195.201:~/angular-deploy/

        ssh -o StrictHostKeyChecking=no rishitpalle@35.228.195.201 "
          # Copy the files from the Angular build to Apache HTML folder
          sudo cp ~/angular-deploy/browser/* /var/www/html/;

          # Ensure correct permissions for Apache
          sudo chmod -R 755 /var/www/html;

          # Restart Apache to serve the updated app
          sudo systemctl restart apache2;
        "
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
